### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by marcocrotti69** [jointag/JTProximitySDK-Cordova#2]
With installation command (cordova plugin add cordova-plugin-jointag-proximity --save --variable KARIBOO_ID="YOUR_API_KEY" --variable KARIBOO_SECRET="YOUR_API_SECRET"). I have thi error:
'cordova-plugin-jointag-proximity' is not in the npm registry

**Comment by dawit-io** [comment]
@marcocrotti69 maybe you were following instructions on develop branch, 
the correct command is: 
`cordova plugin add @jointag/cordova-plugin-jointag-proximity --save --variable KARIBOO_ID="YOUR_API_KEY" --variable KARIBOO_SECRET="YOUR_API_SECRET"`
Anyway you can find more informations here: https://www.npmjs.com/package/@jointag/cordova-plugin-jointag-proximity

**Comment by marcocrotti69** [comment]
Ok. Still persit the error in plugin.xml. This file stard with d not <

**Comment by dawit-io** [comment]
Now it should be fixed
